# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-21 12:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('middle_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('', ''), ('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('birthday', models.DateField(default=datetime.date.today, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=13)),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('profession', models.CharField(choices=[('', ''), ('AMP', 'Allied Medical Professional'), ('DEN', 'Dentist'), ('DIE', 'Dietician'), ('DOC', 'Doctor'), ('COD', 'Medical Coder'), ('MTC', 'Medical Technologist'), ('NUR', 'Nurse'), ('PHA', 'Pharmacist'), ('REC', 'Recruiter')], default='', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='HD_professionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_experience', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OH_professionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oh_experience', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=250)),
                ('when', models.DateField()),
                ('time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('where', models.CharField(max_length=250)),
                ('who', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_given', models.DateTimeField()),
                ('incentives', models.TextField()),
                ('incentives_given', models.DateTimeField()),
                ('requirements', models.TextField()),
                ('expected_number_patients', models.IntegerField()),
                ('person_to_relieve', models.CharField(max_length=250)),
                ('toxicity', models.IntegerField()),
                ('reviews', models.TextField(default='Type Here.')),
                ('is_taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('license_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cancellations', models.IntegerField(default=0)),
                ('bookings', models.IntegerField(default=0)),
                ('preference', models.CharField(choices=[('', ''), ('BOTH', 'Reliever & Regular Posts'), ('RELI', 'Reliever Posts'), ('REGU', 'Regular Posts')], default='', max_length=4)),
                ('professional_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=250)),
                ('recruiter_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomate_status', models.BooleanField(default=False)),
                ('consultant_status', models.BooleanField(default=False)),
                ('license_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Professionals')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='specialists',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Specialties'),
        ),
        migrations.AddField(
            model_name='post',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Professionals'),
        ),
        migrations.AddField(
            model_name='oh_professionals',
            name='oh_license_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Professionals'),
        ),
        migrations.AddField(
            model_name='hd_professionals',
            name='hd_license_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Professionals'),
        ),
    ]
